import { makeMeta } from '../lib/provenance.mjs';

/**
 * Zone catalog — approximated from original world.js (gap G-LISTZONE).
 * 13 zones: 1 player, 5 theWarlord, 6 thePrincess, 1 thePsychopath.
 * 8 aiStates, 4 factions, 3 policies.
 * iter-016 M7a-1 T1.
 */
export function extractZones() {
  return {
    _meta: makeMeta('doc/original_source', 'approximated', 'listZone not fully extracted; gap G-LISTZONE'),
    zones: {
      policies: [
        { id: 0, name: 'Resource',  desc: 'Focus on resource extraction and gold production.' },
        { id: 1, name: 'Growth',    desc: 'Focus on population growth.' },
        { id: 2, name: 'Military',  desc: 'Focus on military recruitment.' },
      ],
      aiStates: [
        { id: 0, name: 'Neutral',    desc: 'Neither friendly nor hostile.' },
        { id: 1, name: 'Friendly',   desc: 'Willing to trade and cooperate.' },
        { id: 2, name: 'Tense',      desc: 'Suspicious; may turn hostile.' },
        { id: 3, name: 'Hostile',    desc: 'Actively opposing the player.' },
        { id: 4, name: 'AtWar',      desc: 'In open conflict with the player.' },
        { id: 5, name: 'Subjugated', desc: 'Under player control via tribute.' },
        { id: 6, name: 'Allied',     desc: 'Full military alliance with player.' },
        { id: 7, name: 'Vassal',     desc: 'Owes tribute and follows orders.' },
      ],
      factions: [
        {
          id: 'player',
          name: 'The Settlement',
          desc: 'The player\'s home faction.',
          color: '#4CAF50',
          aggression: 0,
          backstab: 0,
          allies: [],
          recallMin: { w: 0, a: 0 },
          unitStats: {
            warriors: { strength: 1, defense: 1 },
            archers:  { strength: 1, defense: 1 },
          },
        },
        {
          id: 'theWarlord',
          name: 'The Warlord',
          desc: 'A ruthless military commander seeking domination.',
          color: '#F44336',
          workerGrowthMulti: 1.5,
          archerGrowthMulti: 1.3,
          capitalId: 'silverInslet',
          aggression: 0.7,
          backstab: 0.3,
          allies: [],
          recallMin: { w: 20, a: 10 },
          unitStats: {
            warriors: { strength: 2, defense: 1 },
            archers:  { strength: 1, defense: 2 },
          },
        },
        {
          id: 'thePrincess',
          name: 'The Princess',
          desc: 'A noble ruler balancing diplomacy and military strength.',
          color: '#9C27B0',
          workerGrowthMulti: 0.6,
          archerGrowthMulti: 1.6,
          capitalId: 'kitsilano',
          aggression: 0.4,
          backstab: 0.5,
          allies: [],
          recallMin: { w: 10, a: 20 },
          unitStats: {
            warriors: { strength: 1, defense: 2 },
            archers:  { strength: 2, defense: 1 },
          },
        },
        {
          id: 'thePsychopath',
          name: 'The Psychopath',
          desc: 'An unpredictable warlord known for overwhelming force.',
          color: '#FF5722',
          workerGrowthMulti: 2.0,
          archerGrowthMulti: 0.5,
          capitalId: 'hornCastle',
          aggression: 0.9,
          backstab: 0.8,
          allies: [],
          recallMin: { w: 40, a: 10 },
          unitStats: {
            warriors: { strength: 3, defense: 1 },
            archers:  { strength: 1, defense: 1 },
          },
        },
      ],
      zones: [
        {
          id: 'homeZone',
          name: 'Home Settlement',
          provenance: 'approximated',
          originalLiege: 'player',
          liege: 'player',
          policy: 0,
          numWorkers: 0,
          targetWorkerNum: 0,
          warriors: 0,
          archers: 0,
          warriorGrowth: 0,
          archerGrowth: 0,
          resources: {},
          tribute: {},
          favour: 0,
          goldStore: 0,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: [],
          capital: true,
        },
        {
          id: 'dickinsonLanding',
          name: 'Dickinson Landing',
          provenance: 'approximated',
          originalLiege: 'theWarlord',
          liege: 'theWarlord',
          policy: 2,
          numWorkers: 420,
          targetWorkerNum: 500,
          warriors: 55,
          archers: 30,
          warriorGrowth: 3,
          archerGrowth: 2,
          resources: { wood: 80, stone: 40 },
          tribute: {},
          favour: 0,
          goldStore: 6000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['pointAnne', 'homeZone'],
        },
        {
          id: 'pointAnne',
          name: 'Point Anne',
          provenance: 'approximated',
          originalLiege: 'theWarlord',
          liege: 'theWarlord',
          policy: 0,
          numWorkers: 380,
          targetWorkerNum: 450,
          warriors: 40,
          archers: 25,
          warriorGrowth: 2,
          archerGrowth: 2,
          resources: { food: 60, gold: 20 },
          tribute: {},
          favour: 0,
          goldStore: 5500,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['dickinsonLanding', 'redWater'],
        },
        {
          id: 'redWater',
          name: 'Red Water',
          provenance: 'approximated',
          originalLiege: 'theWarlord',
          liege: 'theWarlord',
          policy: 2,
          numWorkers: 500,
          targetWorkerNum: 600,
          warriors: 70,
          archers: 40,
          warriorGrowth: 4,
          archerGrowth: 2,
          resources: { iron: 50, stone: 30 },
          tribute: {},
          favour: 0,
          goldStore: 7500,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['pointAnne', 'tomiko'],
        },
        {
          id: 'tomiko',
          name: 'Tomiko',
          provenance: 'approximated',
          originalLiege: 'theWarlord',
          liege: 'theWarlord',
          policy: 1,
          numWorkers: 600,
          targetWorkerNum: 700,
          warriors: 50,
          archers: 35,
          warriorGrowth: 3,
          archerGrowth: 2,
          resources: { wood: 100, food: 80 },
          tribute: {},
          favour: 0,
          goldStore: 9000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['redWater', 'silverInslet'],
        },
        {
          id: 'silverInslet',
          name: 'Silver Inslet',
          provenance: 'approximated',
          originalLiege: 'theWarlord',
          liege: 'theWarlord',
          policy: 0,
          numWorkers: 700,
          targetWorkerNum: 800,
          warriors: 80,
          archers: 50,
          warriorGrowth: 5,
          archerGrowth: 3,
          resources: { silver: 120, gold: 60 },
          tribute: {},
          favour: 0,
          goldStore: 12000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['tomiko'],
          capital: true,
        },
        {
          id: 'castleGrey',
          name: 'Castle Grey',
          provenance: 'approximated',
          originalLiege: 'thePrincess',
          liege: 'thePrincess',
          policy: 0,
          numWorkers: 450,
          targetWorkerNum: 550,
          warriors: 35,
          archers: 60,
          warriorGrowth: 2,
          archerGrowth: 4,
          resources: { stone: 90, wood: 50 },
          tribute: {},
          favour: 0,
          goldStore: 7000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['winisk', 'homeZone'],
        },
        {
          id: 'winisk',
          name: 'Winisk',
          provenance: 'approximated',
          originalLiege: 'thePrincess',
          liege: 'thePrincess',
          policy: 1,
          numWorkers: 520,
          targetWorkerNum: 620,
          warriors: 30,
          archers: 55,
          warriorGrowth: 2,
          archerGrowth: 4,
          resources: { food: 110, wood: 70 },
          tribute: {},
          favour: 0,
          goldStore: 8000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['castleGrey', 'burwash'],
        },
        {
          id: 'burwash',
          name: 'Burwash',
          provenance: 'approximated',
          originalLiege: 'thePrincess',
          liege: 'thePrincess',
          policy: 0,
          numWorkers: 480,
          targetWorkerNum: 560,
          warriors: 28,
          archers: 50,
          warriorGrowth: 2,
          archerGrowth: 3,
          resources: { iron: 60, stone: 45 },
          tribute: {},
          favour: 0,
          goldStore: 7200,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['winisk', 'corbyville'],
        },
        {
          id: 'corbyville',
          name: 'Corbyville',
          provenance: 'approximated',
          originalLiege: 'thePrincess',
          liege: 'thePrincess',
          policy: 2,
          numWorkers: 550,
          targetWorkerNum: 650,
          warriors: 45,
          archers: 70,
          warriorGrowth: 3,
          archerGrowth: 5,
          resources: { wood: 85, food: 65 },
          tribute: {},
          favour: 0,
          goldStore: 8500,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['burwash', 'lemieux'],
        },
        {
          id: 'lemieux',
          name: 'Lemieux',
          provenance: 'approximated',
          originalLiege: 'thePrincess',
          liege: 'thePrincess',
          policy: 1,
          numWorkers: 620,
          targetWorkerNum: 720,
          warriors: 40,
          archers: 75,
          warriorGrowth: 2,
          archerGrowth: 5,
          resources: { food: 130, gold: 40 },
          tribute: {},
          favour: 0,
          goldStore: 9500,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['corbyville', 'kitsilano'],
        },
        {
          id: 'kitsilano',
          name: 'Kitsilano',
          provenance: 'approximated',
          originalLiege: 'thePrincess',
          liege: 'thePrincess',
          policy: 0,
          numWorkers: 750,
          targetWorkerNum: 850,
          warriors: 45,
          archers: 90,
          warriorGrowth: 3,
          archerGrowth: 6,
          resources: { silver: 100, gold: 80 },
          tribute: {},
          favour: 0,
          goldStore: 13000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: false,
          neighbours: ['lemieux'],
          capital: true,
        },
        {
          id: 'hornCastle',
          name: 'Horn Castle',
          provenance: 'approximated',
          originalLiege: 'thePsychopath',
          liege: 'thePsychopath',
          policy: 2,
          numWorkers: 900,
          targetWorkerNum: 1000,
          warriors: 150,
          archers: 60,
          warriorGrowth: 10,
          archerGrowth: 3,
          resources: { iron: 200, stone: 150 },
          tribute: {},
          favour: 0,
          goldStore: 20000,
          notEnoughGold: 0,
          curQuest: null,
          immunity: true,
          neighbours: ['dickinsonLanding', 'castleGrey'],
          capital: true,
        },
      ],
    },
  };
}
